tailwind.config = {
  theme: {
    extend: {
      colors: {
        canvas: '#f5f7f9',
        surface: '#f5f7f9',
        sand: '#eaeff5',
        line: '#dbe0e6',
        'on-surface': '#161d26',
        'on-variant': '#4e5661',
        muted: '#4e5661',
        primary: '#081f3c',
        'primary-deep': '#06162a',
        'primary-mid': '#0f3b75',
        'primary-light': '#0c2e5a',
        'primary-soft': '#bdc7d5',
        'primary-bright': '#0f3b75',
        'primary-tint': '#eaeff5',
        'amber-cream': '#eaeff5',
        'amber-soft': '#eaeff5',
        'on-primary': '#ffffff',
        gold: '#0f3b75',
        'gold-light': '#eaeff5',
        'gold-bright': '#9cb5d5',
        'gold-deep': '#0c2e5a',
        champagne: '#eaeff5',
        'gold-tint': '#eaeff5',
        urgent: '#e11d48',
        'urgent-dark': '#be123c',
      },
      fontFamily: {
        sans: ['"Thmanyah Sans"', 'system-ui', 'sans-serif'],
        display: ['"Thmanyah Serif Display"', 'serif'],
        serif: ['"Thmanyah Serif Display"', 'serif'],
        text: ['"Thmanyah Serif Text"', 'serif'],
      },
      maxWidth: { page: '1280px' },
      boxShadow: {
        card: '0 1px 2px rgba(22,29,38,.04), 0 10px 30px -14px rgba(8,31,60,.16)',
        lift: '0 28px 56px -22px rgba(8,31,60,.32), 0 8px 18px -8px rgba(8,31,60,.10)',
        glow: '0 16px 36px -12px rgba(15,59,117,.55)',
      },
    },
  },
};
