<?php

namespace App\Support;

/** GENERATED: Material Symbols names an editor may pick for cards (all verified to exist in the bundled icon font). */
final class SiteTextsIcons
{
    public const ALL = [
        'crisis_alert' => 'إغاثة عاجلة',
        'construction' => 'إنشاءات',
        'trending_up' => 'تنمية',
        'health_and_safety' => 'صحة وسلامة',
        'medical_services' => 'خدمات طبية',
        'local_hospital' => 'مستشفى',
        'medication' => 'دواء',
        'volunteer_activism' => 'عطاء',
        'favorite' => 'قلب',
        'handshake' => 'مصافحة',
        'diversity_3' => 'مجتمع',
        'groups' => 'مجموعة',
        'group' => 'أفراد',
        'person' => 'شخص',
        'family_restroom' => 'أسرة',
        'child_care' => 'أطفال',
        'elderly' => 'كبار السن',
        'school' => 'تعليم',
        'menu_book' => 'كتب',
        'restaurant' => 'وجبات',
        'soup_kitchen' => 'مطبخ ميداني',
        'bakery_dining' => 'مخبز',
        'nutrition' => 'تغذية',
        'water_drop' => 'مياه',
        'camping' => 'خيام',
        'house' => 'مأوى',
        'apartment' => 'مبنى',
        'engineering' => 'هندسة',
        'handyman' => 'صيانة',
        'local_shipping' => 'قوافل',
        'inventory_2' => 'مخزون',
        'public' => 'دولي',
        'location_on' => 'موقع',
        'hub' => 'غرفة عمليات',
        'map' => 'خريطة',
        'shield' => 'حماية',
        'verified' => 'موثّق',
        'verified_user' => 'أمان',
        'balance' => 'عدالة',
        'bolt' => 'سرعة',
        'photo_camera' => 'تصوير',
        '4k' => 'فيديو',
        'summarize' => 'تقارير',
        'fact_check' => 'تدقيق',
        'task_alt' => 'إنجاز',
        'travel_explore' => 'رصد',
        'flag' => 'علم',
        'star' => 'نجمة',
        'workspace_premium' => 'تميّز',
        'lightbulb' => 'فكرة',
        'target' => 'هدف',
        'eco' => 'بيئة',
        'emergency' => 'طوارئ',
        'ac_unit' => 'شتاء',
        'call' => 'اتصال',
        'mail' => 'بريد',
        'chat' => 'محادثة',
        'support_agent' => 'دعم',
        'schedule' => 'وقت',
        'event' => 'فعالية',
        'calendar_month' => 'تقويم',
        'timeline' => 'مسيرة',
        'campaign' => 'حملة',
        'record_voice_over' => 'صوت',
        'visibility' => 'رؤية',
        'diamond' => 'قيم',
        'home' => 'منزل',
        'account_balance' => 'مؤسسة',
        'how_to_reg' => 'تسجيل',
        'cleaning_services' => 'نظافة',
        'accessibility_new' => 'إتاحة',
    ];
}
