<?php

// Permission catalog (source of truth for the UI and for the `permissions` table seed).
// Keys: <module>.<action>. Route -> module mapping used by App\Support\Permissions.
return [
    'actions' => ['view' => 'عرض', 'create' => 'إضافة', 'edit' => 'تعديل', 'delete' => 'حذف', 'publish' => 'نشر', 'export' => 'تصدير', 'manage' => 'إدارة'],
    'groups' => [
        ['key' => 'general', 'label' => 'عام', 'modules' => [
            ['key' => 'dashboard', 'label' => 'نظرة عامة', 'icon' => 'space_dashboard', 'actions' => ['view']],
            ['key' => 'reports', 'label' => 'التقارير والإحصائيات', 'icon' => 'monitoring', 'actions' => ['view', 'export']],
        ]],
        ['key' => 'content', 'label' => 'المحتوى', 'modules' => [
            ['key' => 'homepage', 'label' => 'الصفحة الرئيسية', 'icon' => 'home', 'actions' => ['view', 'edit']],
            ['key' => 'projects', 'label' => 'المشاريع', 'icon' => 'volunteer_activism', 'actions' => ['view', 'create', 'edit', 'delete', 'publish']],
            ['key' => 'news', 'label' => 'الأخبار', 'icon' => 'newspaper', 'actions' => ['view', 'create', 'edit', 'delete', 'publish']],
            ['key' => 'tags', 'label' => 'الوسوم', 'icon' => 'sell', 'actions' => ['view', 'create', 'edit', 'delete']],
            ['key' => 'gallery', 'label' => 'معرض الصور', 'icon' => 'photo_library', 'actions' => ['view', 'create', 'edit', 'delete', 'publish']],
            ['key' => 'media', 'label' => 'مكتبة الوسائط', 'icon' => 'perm_media', 'actions' => ['view', 'create', 'edit', 'delete']],
            ['key' => 'stories', 'label' => 'قصص الميدان', 'icon' => 'format_quote', 'actions' => ['view', 'create', 'edit', 'delete', 'publish']],
            ['key' => 'activities', 'label' => 'الأنشطة الميدانية', 'icon' => 'event_available', 'actions' => ['view', 'create', 'edit', 'delete']],
            ['key' => 'partners', 'label' => 'الشركاء', 'icon' => 'handshake', 'actions' => ['view', 'create', 'edit', 'delete']],
            ['key' => 'faq', 'label' => 'الأسئلة الشائعة', 'icon' => 'help', 'actions' => ['view', 'create', 'edit', 'delete']],
            ['key' => 'appeal', 'label' => 'نداء الإغاثة', 'icon' => 'campaign', 'actions' => ['view', 'create', 'edit', 'delete']],
            ['key' => 'announcements', 'label' => 'الإعلانات', 'icon' => 'notifications_active', 'actions' => ['view', 'create', 'edit', 'delete']],
            ['key' => 'impact', 'label' => 'خريطة الأثر', 'icon' => 'map', 'actions' => ['view', 'edit']],
            ['key' => 'vision', 'label' => 'الرؤية والرسالة والقيم', 'icon' => 'visibility', 'actions' => ['view', 'edit']],
            ['key' => 'pages', 'label' => 'الصفحات', 'icon' => 'web', 'actions' => ['view', 'create', 'edit', 'delete', 'publish']],
            ['key' => 'menu', 'label' => 'القائمة', 'icon' => 'menu_open', 'actions' => ['view', 'create', 'edit', 'delete']],
        ]],
        ['key' => 'communication', 'label' => 'التواصل', 'modules' => [
            ['key' => 'messages', 'label' => 'الرسائل والطلبات', 'icon' => 'inbox', 'actions' => ['view', 'edit', 'delete']],
        ]],
        ['key' => 'system', 'label' => 'النظام', 'modules' => [
            ['key' => 'users', 'label' => 'المستخدمون', 'icon' => 'manage_accounts', 'actions' => ['view', 'create', 'edit', 'delete']],
            ['key' => 'roles', 'label' => 'الأدوار والصلاحيات', 'icon' => 'admin_panel_settings', 'actions' => ['view', 'create', 'edit', 'delete']],
            ['key' => 'settings', 'label' => 'الإعدادات العامة', 'icon' => 'settings', 'actions' => ['view', 'edit']],
            ['key' => 'constants', 'label' => 'ثوابت النظام', 'icon' => 'list_alt', 'actions' => ['view', 'manage']],
            ['key' => 'backup', 'label' => 'النسخ الاحتياطي', 'icon' => 'backup', 'actions' => ['view', 'manage']],
            ['key' => 'audit', 'label' => 'سجل النشاط', 'icon' => 'history', 'actions' => ['view', 'export']],
        ]],
    ],
    'route_modules' => [
        'dashboard' => 'dashboard',
        'notifications' => 'dashboard',
        'reports' => 'reports',
        'newsletter' => 'messages',
        'homepage' => 'homepage',
        'site-texts' => 'pages',
        'hero' => 'homepage',
        'projects' => 'projects',
        'programs' => 'projects',
        'governorates' => 'projects',
        'news' => 'news',
        'articles' => 'news',
        'article-categories' => 'news',
        'tags' => 'tags',
        'gallery' => 'gallery',
        'gallery-items' => 'gallery',
        'gallery-albums' => 'gallery',
        'media' => 'media',
        'stories' => 'stories',
        'activities' => 'activities',
        'partners' => 'partners',
        'faq' => 'faq',
        'faqs' => 'faq',
        'appeal' => 'appeal',
        'appeals' => 'appeal',
        'announcements' => 'announcements',
        'impact' => 'impact',
        'vision' => 'vision',
        'pages' => 'pages',
        'sections' => 'pages',
        'menu' => 'menu',
        'menus' => 'menu',
        'messages' => 'messages',
        'users' => 'users',
        'roles' => 'roles',
        'settings' => 'settings',
        'audit-logs' => 'audit',
        'backup' => 'backup',
        'maintenance' => 'settings',
    ],
    // Signed-in routes any active user may use (no permission needed)
    'free_routes' => ['search', 'profile', 'legacy-html', 'login', 'logout', 'password', 'status', 'notifications'],
];
