<?php

// Default General Settings (derived from DEF in admin-settings.js). Used by `php artisan almel:sync-settings`.
// Section => [path => default]. Donations settings are intentionally not stored here.
return [
    'general' => [
        'orgName' => 'جمعية الشمال للتنمية والتطوير المجتمعي',
        'tagline' => 'لإغاثة أهل غزة ودعم صمودهم',
        'license' => 'GZA-77492',
        'website' => 'https://shamal-society.org',
        'email' => 'info@shamal-society.org',
        'phone' => '0592945557',
        'address' => 'مكتب إغاثة غزة — القاهرة (تنسيق دخول المساعدات)',
        'logo' => '',
        'favicon' => '',
        'timezone' => 'Asia/Gaza',
        'language' => 'ar',
        'dateFormat' => 'long',
        'maintenance' => false,
        'maintenanceMsg' => 'نجري تحديثات لتحسين تجربتك، وسنعود خلال وقت قصير. شكراً لصبركم.',
        'hoursText' => 'الأحد - الخميس • 8:00 ص - 4:00 م',
        'heroStat1Value' => '180K+', 'heroStat1Label' => 'مستفيد في غزة',
        'heroStat2Value' => '5', 'heroStat2Label' => 'محافظات القطاع',
        'heroStat3Value' => '+2,500', 'heroStat3Label' => 'مقطع موثّق من غزة',
        'heroStat4Value' => '98.4%', 'heroStat4Label' => 'نسبة الشفافية والتدقيق',
    ],
    'appearance' => [
        'theme' => 'light',
        'accent' => '#f28c14',
        'scale' => 'md',
        'density' => 'comfortable',
        'sidebar' => 'navy',
        'radius' => 'md',
    ],
    'users' => [
        'matrix' => [
            'admin' => [
                'projects_view' => true,
                'projects_edit' => true,
                'news_publish' => true,
                'pages_edit' => true,
                'messages_reply' => true,
                'reports_export' => true,
                'users_manage' => true,
                'settings_edit' => true,
                'backup_run' => true,
            ],
            'editor' => [
                'projects_view' => true,
                'projects_edit' => true,
                'news_publish' => true,
                'pages_edit' => true,
                'messages_reply' => true,
                'reports_export' => true,
                'users_manage' => false,
                'settings_edit' => false,
                'backup_run' => false,
            ],
            'writer' => [
                'projects_view' => true,
                'projects_edit' => false,
                'news_publish' => true,
                'pages_edit' => false,
                'messages_reply' => true,
                'reports_export' => false,
                'users_manage' => false,
                'settings_edit' => false,
                'backup_run' => false,
            ],
            'viewer' => [
                'projects_view' => true,
                'projects_edit' => false,
                'news_publish' => false,
                'pages_edit' => false,
                'messages_reply' => false,
                'reports_export' => false,
                'users_manage' => false,
                'settings_edit' => false,
                'backup_run' => false,
            ],
        ],
        'custom' => [],
    ],
    'security' => [
        'minLength' => 10,
        'upper' => true,
        'number' => true,
        'symbol' => false,
        'reuse' => 5,
        'expiry' => '90',
        'lockout' => 5,
        'enforce2fa' => 'admins',
        'alertNewDevice' => true,
        'alertFailed' => true,
        'alertCountry' => true,
        'timeout' => '60',
        'ipAllow' => false,
        'ips' => [
            '203.0.113.0/24',
            '198.51.100.24',
        ],
    ],
    'notifications' => [
        'matrix' => [
            'newsletter_new' => [
                'email' => false,
                'app' => true,
                'sms' => false,
            ],
            'news_draft' => [
                'email' => false,
                'app' => true,
                'sms' => false,
            ],
            'user_new' => [
                'email' => false,
                'app' => true,
                'sms' => false,
            ],
            'backup_failed' => [
                'email' => true,
                'app' => true,
                'sms' => false,
            ],
            'maintenance_toggle' => [
                'email' => false,
                'app' => true,
                'sms' => false,
            ],
            'login_failed' => [
                'email' => true,
                'app' => true,
                'sms' => false,
            ],
            'message_new' => [
                'email' => true,
                'app' => true,
                'sms' => false,
            ],
            'volunteer' => [
                'email' => false,
                'app' => true,
                'sms' => false,
            ],
            'project_goal' => [
                'email' => false,
                'app' => true,
                'sms' => false,
            ],
            'project_urgent' => [
                'email' => true,
                'app' => true,
                'sms' => false,
            ],
            'news_scheduled' => [
                'email' => false,
                'app' => true,
                'sms' => false,
            ],
            'security_login' => [
                'email' => true,
                'app' => true,
                'sms' => true,
            ],
            'backup_done' => [
                'email' => true,
                'app' => true,
                'sms' => false,
            ],
            'weekly' => [
                'email' => true,
                'app' => false,
                'sms' => false,
            ],
        ],
        'quiet' => true,
        'quietFrom' => '22:00',
        'quietTo' => '07:00',
        'digest' => 'weekly',
        'digestDay' => 'sun',
        'digestEmail' => 'admin@shamal-society.org',
    ],
    'seo' => [
        'titleTpl' => '%s — جمعية الشمال للتنمية والتطوير المجتمعي',
        'metaDesc' => 'مؤسسة إنسانية تعمل على إغاثة أهل غزة: الغذاء والدواء والمأوى ورعاية الأيتام وفق معايير الحوكمة والشفافية.',
        'index' => true,
        'sitemap' => true,
        'ogImage' => '/assets/site/img/hero-poster.jpg',
        'social' => [
            'facebook' => 'facebook.com/shamal.society',
            'x' => 'x.com/shamal_society',
            'instagram' => 'instagram.com/shamal.society',
            'youtube' => 'youtube.com/@shamalsociety',
            'telegram' => '',
            'whatsapp' => 'wa.me/972592945557',
        ],
        'analyticsId' => '',
        'anonymizeIp' => true,
        'cookieBanner' => true,
    ],
    'backup' => [
        'schedule' => 'weekly',
        'time' => '03:00',
        'keep' => 10,
        'incContent' => true,
        'incSettings' => true,
        'incMedia' => false,
        'dest' => 'local',
    ],
];
